Add Qt X11 Extras to README
Lurkki14/tuxclocker pull request #42
Opened 2020-09-16 20:20 UTC by Bengt

2020-09-16 20:23 UTC, Bengt commented
This is under Ubuntu 18.04.

2020-09-17 10:07 UTC, Lurkki14 commented
You should add a separate (and more complete) section for Ubuntu since these package names aren't universally applicable.

2020-09-17 20:43 UTC, Bengt commented
I added a Prerequisites section for the OS-level dependencies and made them valid instructions for Ubuntu. I tested against 18.04, so maybe package names are slightly different for other iterations.

2020-09-18 13:28 UTC, Lurkki14 requested changes

2020-09-18 13:28 UTC, Lurkki14 commented on README.md
> -- NOTE: headers are usually included in a package named \*-dev, if they are separate
This shouldn't be removed, since it's intended to be a general directive.

2020-09-18 13:28 UTC, Lurkki14 commented on README.md
> -- NOTE: headers are usually included in a package named \*-dev, if they are separate
The same goes for this.

2020-09-18 13:29 UTC, Lurkki14 requested changes

2020-09-18 13:29 UTC, Lurkki14 commented on README.md
> -- qt5base, x11extras and their headers
This shouldn't be removed, since it's supposed to be a general directive.

2020-09-18 13:29 UTC, Lurkki14 commented on README.md
> -- libdrm and headers
The same goes for this

2020-09-20 16:29 UTC, Bengt commented
@Lurkki14 I put the distribution-agnostic instructions back in. I hope this is now satisfactory.

2020-09-21 09:56 UTC, merged

2020-09-21 10:53 UTC, Bengt commented
Thanks for the merge.

2020-09-21 13:29 UTC, Lurkki14 commented
Looks good, merged.