86 add monitor
Lurkki14/tuxclocker pull request #87
Opened 2023-12-30 21:19 UTC by snorkellingcactus

Selection does not work as ideal
I messed up the layout by inserting the monitor widget
I weren't able to get double values from the dbus interface

2023-12-30 22:03 UTC, Lurkki14 requested changes

2023-12-30 22:03 UTC, Lurkki14 commented on src/tuxclocker-qt/monitor/Monitor.cpp
> +  xAxis->setTickLabelColor(QColor(200, 200, 200));
Colors shouldn't be hardcoded https://doc.qt.io/qt-6/qpalette.html#color-1

2023-12-31 16:52 UTC, snorkellingcactus commented on src/tuxclocker-qt/meson.build
> +		'monitor/qcustomplot.h',
No special reason, i can try to use Qt charts. I've just started with this and then discovered your project and qt charts. I can compare them after doing a qt chart version.

2023-12-31 16:52 UTC, snorkellingcactus commented on src/tuxclocker-qt/monitor/Metric.cpp
> +#include "Metric.hpp"
I'll try that

2023-12-31 16:53 UTC, snorkellingcactus commented on src/tuxclocker-qt/monitor/Monitor.cpp
> +  timeTicker->setTimeFormat("%m:%s:%z");
Sure

2024-12-21 04:14 UTC, closed without merging